name: main

on:
  pull_request:
    branches: [ main ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    name: PHP CS FIXER
    steps:
      - uses: actions/checkout@v3
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run
  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
        os: [windows-latest]
        dependencies: [ 'lowest', 'highest' ]
    continue-on-error: ${{ matrix.os == 'windows-latest' && matrix.php != '8.1' }}
    name: PHP ${{ matrix.php }} - OS ${{ matrix.os }} - Dependencies ${{ matrix.dependencies }}
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            extensions: curl, zip, rar, bz2
            coverage: pcov
            tools: composer:v2
      - name: Install unrar on Ubuntu
        run: sudo apt install unrar
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Install unrar on MacOS
        run: brew install rar
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Install pacman dependencies (Windows)
        shell: cmd
        run: |
          set "PATH=%PATH%;c:\msys64\usr\bin"
          pacman -S --noconfirm --needed unrar
        if: ${{ matrix.os == 'windows-latest' }}
      - name: Validate composer.json
        run: composer validate
      - uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: "--no-progress --no-suggest"
      - name: Run tests (*NIX)
        run: ./vendor/bin/phpunit
        if: ${{ matrix.os != 'windows-latest' }}
      - name: Run tests (Windows)
        run: |
          set "PATH=%PATH%;c:\msys64\usr\bin"
          ./vendor/bin/phpunit
        if: ${{ matrix.os == 'windows-latest' }}
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=clover.xml -v
        if: ${{ github.event_name == 'push' && matrix.os == 'ubuntu-latest' && matrix.php == '8.1' && matrix.dependencies == 'highest' }}
